### ISSUE TITLE
datapack error loading existing worlds

### ISSUE THREAD

**Issue by LlubNek** [MysticMods/MysticalBiomes#1]
### General Information

**Describe the bug:**
While I can create a new world just fine, loading an existing world results in a datapack error.
Blame reports this is likely caused by a problem with the mushroom hut structure:
```
[17:34:30] [Render thread/ERROR] [co.te.bl.Blame/]: 
****************** Blame Report 1.8.1 ******************

 A crash is most likely going to happen right after this report!
 It seems mysticalbiomes:mushroom_hut | mysticalbiomes:mushroom_hut is the cause because it is not added 
 to the FlatGenerationSettings.STRUCTURES map. Please let the mod owner 
 of that structure know about this crash. That way they can add their structure 
 to that map since someone is trying to spawn it in a flat/custom dimension. 

[17:34:29] [Render thread/ERROR] [minecraft/SaveFormat]: Exception reading D:\_gdl\instances\1.16.4-forge-20210102\saves\sp20\level.dat
java.lang.NullPointerException: null
	at net.minecraft.world.biome.BiomeGenerationSettings.lambda$getStructure$8(BiomeGenerationSettings.java:86) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.BiomeGenerationSettingsAccessor,pl:mixin:A}
...
```

**To Reproduce:**
1. create a world
2. exit minecraft
3. restart minecraft
4. reenter world
5. observe error

**Expected behavior:**
Normal start with no warnings or errors.

### Environment Versions

**Mystic Mods Versions**
mysticalbiomes-1.16.4-0.0.0.1.jar
mysticalmachinery-1.16.4-0.0.3.9.jar
mysticalpowers-1.16.4-0.0.1.6.jar
mysticalworld-1.16.4-0.3.1.6.jar

**Other Versions:**
- Forge: 35.1.36
- Minecraft: 1.16.4
 blame-forge-1.16.3/1.16.4-1.8.1

### Logging Information
**Latest Log (if necessary):**
[latest.log](https://github.com/MysticMods/MysticalBiomes/files/5805540/latest.log)

### Additional Information
**Screenshots (if available):**
![image](https://user-images.githubusercontent.com/313762/104389294-1af0fe00-5509-11eb-9b4d-7465563c46c9.png)

**Comment by noobanidus** [comment]
Thanks! Let me triple-check why this is happening, I thought I was doing that bit properly.

**Comment by noobanidus** [comment]
Yeah, this is my fault entirely. I've uploaded a new version to CurseForge and it looks like it's just been approved. Let me know if you still have issues!
