### ISSUE TITLE
Aubergine Duplication

### ISSUE THREAD

**Issue by AlleCraft-alterego** [MysticMods/MysticalBiomes#2]
Mystrical Biomes spawn aubergine with grow stage 0 and with pickle tweaks right click aubergine have a duplication (aubergine crop place on farmland manually or command, pickle tweaks right click not work)

exemple: https://youtu.be/7pXdx2XkJG0

and.... aubergine crop block don't have block tag "minecraft:crops"

Minecraft: 1.16.5
Forge: 36.0.43
MysticalWorld: 0.3.1.8
MysticalBiomes: 0.0.0.3
PickleTweaks: 5.2.1

**Comment by noobanidus** [comment]
Damn, I was afraid this was going to come back and haunt me. I should've just made it a normal bush block instead of a crop... but good to know! Thanks.

**Comment by noobanidus** [comment]
This will be fixed in the next release of Mystical World for 1.16.

**Comment by AlleCraft-alterego** [comment]
perfect

**Comment by noobanidus** [comment]
You'll need to update Mystical World rather than Mystical Biomes to fix this, but it should be fixed. It's now just a standard bush with drops, instead of being considered a crop.
