### ISSUE TITLE
Crash w/ Mystical World

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalBiomes#3]
`Minecraft v1.16.5`
`Forge v36.1.24`
`Mystical World v0.3.2.13`
`Mystical Biomes v0.0.0.3`

After updating Mystical World to the latest version, Mystical Biomes now crashes.
[Crash Report](https://gist.github.com/WenXin20/9a389f7b0164f817f9c81b62f7093d7f)

**Comment by noobanidus** [comment]
Yeah, I forgot to push all the updates to the dependent mods. I'll be doing them shortly. For now, you'll need to use an older version of Mystical World with it.

**Comment by WenXin20** [comment]
Cool, sounds good. I tried using the older version, but for some reason I can't join my server if it is missing a registered block, in this case the dynamic tree branch that came with the new update. I already know it's unrelated to this mod since it has happened with other mods before, but I've no idea what causes it.

**Comment by noobanidus** [comment]
The release to fix this should be out.

**Comment by WenXin20** [comment]
Thanks!
